name: 🚀 Auto Deploy to EC2 on Main Push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout Code
      uses: actions/checkout@v3

    - name: 🔐 Setup SSH Key
      run: |
        echo "$EC2_KEY" > private_key.pem
        chmod 600 private_key.pem

    - name: 📤 Copy setup.sh to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i private_key.pem setup.sh ${{ secrets.EC2_HOST }}:/home/ec2-user/setup.sh

    - name: 🚀 SSH into EC2 and run setup.sh (Amazon Linux 2023)
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_HOST }} "
          sudo dnf install -y dos2unix
          dos2unix setup.sh
          chmod +x setup.sh
          ./setup.sh | tee ~/setup_exec.log
          rm -f setup.sh
        "
